"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/

+--------------------------------------------------------------------------------------------------+
|                                            yugabyted                                             |
+--------------------------------------------------------------------------------------------------+
| Status              : Running                                                                    |
| Web console         : http://127.0.0.1:7000                                                      |
| JDBC                : jdbc:postgresql://127.0.0.1:5433/yugabyte?user=yugabyte&password=yugabyte  |
| YSQL                : bin/ysqlsh   -U yugabyte -d yugabyte                                       |
| YCQL                : bin/ycqlsh   -u cassandra                                                  |
| Data Dir            : /home/django/django_project/django_project/yugabyte-2.5.1.0/var/data       |
| Log Dir             : /home/django/django_project/django_project/yugabyte-2.5.1.0/var/logs       |
| Universe UUID       : 88e2c016-bbf6-4b1c-9722-e3abe6ffd2ce                                       |
+--------------------------------------------------------------------------------------------------+
🚀 yugabyted started successfully! To load a sample dataset, try 'yugabyted demo'.
🎉 Join us on Slack at https://www.yugabyte.com/slack
👕 Claim your free t-shirt at https://www.yugabyte.com/community-rewards/

./bin/yb-master --master_addresses 127.0.0.1:7100 -rpc_bind_addresses 127.0.0.1:7100 --fs_data_dirs "/home/django/django_project/django_project/var/data" --placement_cloud aws --placement_region us-west --placement_zone us-west-2a  --replication_factor=1  &
./bin/yb-tserver --master_addresses 127.0.0.1:7100 -rpc_bind_addresses 127.0.0.1:9100 --start_pgsql_proxy --pgsql_proxy_bind_address 127.0.0.1:5433 --cql_proxy_bind_address 127.0.0.1:9042 --redis_proxy_bind_address 127.0.0.1:6379 --fs_data_dirs "/home/django/django_project/django_project/var/data" --placement_cloud aws --placement_region us-west --placement_zone us-west-2a
./bin/yb-admin --master_addresses 127.0.0.1:7100 setup_redis_table
"""

import os, sys
import netifaces
import mimetypes

mimetypes.add_type("image/svg+xml", ".svg", True)
mimetypes.add_type("image/svg+xml", ".svgz", True)

REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_PASSWORD = None

REDIS_COUNTRIES_KEY = "CSApi:Private:Contries"

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/bin/")
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/")
COUNTRY_CACHE_FILE = os.path.dirname(os.path.abspath(__file__)) + "/bin/" + '/countries.json'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bbce3d5661faaf3757553b78dc119f57'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Find out what the IP addresses are at run time
# This is necessary because otherwise Gunicorn will reject the connections
def ip_addresses():
	ip_list = []
	for interface in netifaces.interfaces():
		addrs = netifaces.ifaddresses(interface)
		for x in (netifaces.AF_INET, netifaces.AF_INET6):
			if x in addrs:
				ip_list.append(addrs[x][0]['addr'])
	return ip_list


ALLOWED_HOSTS = ['consoleapi.com']

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'easy_timezones',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_user_agents'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

MIDDLEWARE_CLASSES = ('easy_timezones.middleware.EasyTimezoneMiddleware', )

ROOT_URLCONF = 'django_project.urls'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.dirname(os.path.abspath(__file__)) + '/views/',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'django',
        'USER': 'django',
        'PASSWORD': '8b37fc90790f4178fc6ff9aaaf3030d9',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
